### ISSUE TITLE
Special characters are ignored by the formatters in the output

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-js#21]
The markdown includes special characters that help form constructs such as:

Text modifier - (text)[key:’value’;key;key:’value’)
Header - #[ key:’value’; key:’value’]
Audio - ![‘url’]

When these special characters are included in non-markdown text or as the text portion of the text modifier,these characters are not rendering even though they should.

For example, the following Speech Markdown:

```
This is text with (parens) but this and other special characters: []()*~`@#\\_!+- are ignored
```

Is currently being rendered as:
```
<speak>
This is text with parens but this and other special characters:  are ignored
</speak>
```

When instead it should be rendered as: 
```
<speak>
This is text with (parens) but this and other special characters: []()*~`@#\\_!+- are ignored
</speak>
```

**Comment by rmtuckerphx** [comment]
See skipped tests in `modifier-text-allowed-chars.spec.ts`

**Comment by cdiggins** [comment]
Looking at: 
`this.inline = m.choice(this.textModifier, this.emphasis, this.shortBreak, this.breakStrength, this.breakTime, this.audio, this.plainText, this.any).unless(m.newLine);`

Maybe you just need to create a new named rule to replace the 'this.any`. For example:

`this.specialChar = m.newLine;`
    
And then:

`this.inline = m.choice(this.textModifier, this.emphasis, this.shortBreak, this.breakStrength, this.breakTime, this.audio, this.plainText, this.specialChar).unless(m.newLine);`

Your formatter will then be able to handle `specialChar` and pass it through. 

I hope this helps.
