### ISSUE TITLE
Limitation to Node engine below 11

### ISSUE THREAD

**Issue by beevelop** [speechmarkdown/speechmarkdown-js#24]
The `package.json` limits the Node.js engine to below Node 11. This has some impact on our CI / CD pipelines as some of them are already running on Node 11 / 12. Is there any need for that limitation?

**Comment by JochenHeizmann** [comment]
Use --ignore-engines as option for yarn to fix it temporary.

**Comment by rmtuckerphx** [comment]
Since this library will be used in Alexa skills hosted on AWS Lambda and that the max supported version of Lambda is Node.js 10 then I capped the version. See https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Tell me more about how you are using this library.

**Comment by rmtuckerphx** [comment]
![image](https://user-images.githubusercontent.com/247472/61388105-3cb5ea00-a86c-11e9-95fa-07b45a08b5cd.png)

**Comment by beevelop** [comment]
Thank you for the quick response. We are using SpeechMarkdown outside of the Alexa / AWS ecosystem and use it to enhance usability when writing SSML. The generated SSML is piped to different SpeechSynthesis engines like Polly, MS TTS, Watson, etc.
