### ISSUE TITLE
Grammar - emphasis short format

### ISSUE THREAD

**Issue by RokasVaitkevicius** [speechmarkdown/speechmarkdown-js#25]
There is an issue with [short emphasis format](https://www.speechmarkdown.org/syntax/emphasis/) using this parser. I think short format emphasis should be separated by whitespaces from both sides in order to get picked up by parser. 
Currently words separated by hyphens, get wrapped in emphasis tag.

`loop-the-loop`

becomes

`loop<emphasis level="none">the</emphasis>loop`

I think in this case it should not get picked up. It should only be wrapped with emphasis when hyphens are separated with whitespaces

`loop -the- loop`

Same happens with other short format emphasis wrappers, even though I agree that they might not be used in a real world word, but words/sayings with hyphens are quite often and they should not be affected.

**Comment by rmtuckerphx** [comment]
Added tests to `emphasis-short.spec.ts` to support this case. Skipped for now.
