### ISSUE TITLE
Support All US IPA Chars

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-js#36]
The full list of IPA characters supported by Alexa is shown here:
https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html#phoneme

This includes the following chars:  d͡ʒ and t͡ʃ

The file `SpeechMarkdownGrammar.ts` has been updated to include those chars, but when testing in `ipa-standard-alphabet-us.spec.ts` the tests error.

Solution: add the chars to the tests and get them to pass.

**Comment by rmtuckerphx** [comment]
@Fleker Can you figure out why adding these chars to the test cause it to fail?

**Comment by Fleker** [comment]
I'll take a look. It may be due to some unicode mismatch.
