### ISSUE TITLE
Support umlauts and other languages

### ISSUE THREAD

**Issue by RokasVaitkevicius** [speechmarkdown/speechmarkdown-js#37]
It seems that myna parser and its 'letters' range doesn't support other languages than english. I spotted that in german it removes umlauts. 
For example:
`würdest du lieber`
after parsing becomes
`wrdest du lieber`.

I have tested other umlauts, same outcome. I guess other languages like french would have the same issue too.

To fix this I guess we can do two things, either fix it in myna parser which is not actively maintained, so I am afraid, that it would be hard to get support from that, or try adding these special letters with other special characters.

**Comment by rmtuckerphx** [comment]
Let's try adding these special letters with other special characters. Anybody else have a suggestion.
Thanks @RokasVaitkevicius

**Comment by digitalica** [comment]
for me this works ok now: in the editor I typed this example and other special chars and i can't reproduce it.

**Comment by arjan** [comment]
seems to work
