### ISSUE TITLE
Add support of Microsoft Azure SSML

### ISSUE THREAD

**Issue by boltomli** [speechmarkdown/speechmarkdown-js#54]
Based on document <https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup>

It's useful and mostly compliant with Alexa with little differences I think. Of course not those special supports.

I'm trying to draft in <https://github.com/boltomli/speechmarkdown-js/tree/add-microsoft-azure-ssml>

**Comment by rmtuckerphx** [comment]
Thanks for the PR
