### ISSUE TITLE
Grammar - telephone not parsing parenthesis or dashes correctly

### ISSUE THREAD

**Issue by rmtuckerphx** [speechmarkdown/speechmarkdown-js#6]
Various tests in `telephone-standard.spec.ts` are commented out.
Need to fix grammar to accept values with parenthesis or dashes. See `SpeechMarkdownGrammar.ts`

**Comment by Fleker** [comment]
Is it really necessary to have the nested parenthesis? ((888) 555-1298)[phone] seems a bit messy.

**Comment by Fleker** [comment]
This should be fixed now.
