### ISSUE TITLE
Dashes in dates get treated as emphasis

### ISSUE THREAD

**Issue by arjan** [speechmarkdown/speechmarkdown-js#73]
When there is a date, formatted with dashes, these dashes still get treated as emphasized text.
So when using `toText` it means the dashes get stripped.

So `2020-10-10` becomes `20201010`. this is quite unexpected.

Note this only is the issue for numbers, for normal words it is ok, `Mother-in-law` for instance stays untouched.

Would it be an option to treat numbers as word characters as well?

**Comment by beevelop** [comment]
Thank you for the updates @arjan 🙏
